// SAD-76 (RC-A): embed the bundled fonts into styles.css as base64 data URIs.
//
// Obsidian reads a plugin's styles.css and injects it as an inline <style>, so a relative
// `url('assets/fonts/…')` resolves against the app origin, not the plugin folder, and the faces never
// load (the UI falls back to Georgia/Arial). Data URIs are the only form that works for every install
// path, including community-store releases that ship only main.js/manifest.json/styles.css.
//
// Source of truth: assets/fonts/*.woff2 (SIL OFL, see LICENSE-FONTS; identical to @fontsource latin
// subsets). Faces match what Prototype/index.html loads: Poppins 400/500/600, Lora 400/500/600/400i,
// JetBrains Mono 400/500.
//
// Usage:  node scripts/embed-fonts.mjs          rewrite the block between the markers in styles.css
//         node scripts/embed-fonts.mjs --check  exit 1 if styles.css is out of date
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const START = '/* @tablify-fonts:start — generated by scripts/embed-fonts.mjs; do not edit */';
export const END = '/* @tablify-fonts:end */';

export const FACES = [
  { family: 'Poppins', file: 'Poppins-Regular.woff2', weight: 400, style: 'normal' },
  { family: 'Poppins', file: 'Poppins-Medium.woff2', weight: 500, style: 'normal' },
  { family: 'Poppins', file: 'Poppins-SemiBold.woff2', weight: 600, style: 'normal' },
  { family: 'Lora', file: 'Lora-Regular.woff2', weight: 400, style: 'normal' },
  { family: 'Lora', file: 'Lora-Italic.woff2', weight: 400, style: 'italic' },
  { family: 'Lora', file: 'Lora-Medium.woff2', weight: 500, style: 'normal' },
  { family: 'Lora', file: 'Lora-SemiBold.woff2', weight: 600, style: 'normal' },
  { family: 'JetBrains Mono', file: 'JetBrainsMono-Regular.woff2', weight: 400, style: 'normal' },
  { family: 'JetBrains Mono', file: 'JetBrainsMono-Medium.woff2', weight: 500, style: 'normal' },
];

export function fontBlock(root = ROOT) {
  const rules = FACES.map(({ family, file, weight, style }) => {
    const b64 = fs.readFileSync(path.join(root, 'assets/fonts', file)).toString('base64');
    return [
      `/* ${family} ${weight}${style === 'italic' ? ' italic' : ''} (assets/fonts/${file}) */`,
      '@font-face {',
      `  font-family: '${family}';`,
      `  src: url('data:font/woff2;base64,${b64}') format('woff2');`,
      `  font-weight: ${weight};`,
      `  font-style: ${style};`,
      '  font-display: swap;',
      '}',
    ].join('\n');
  });
  return [START, ...rules, END].join('\n');
}

export function embed(css, root = ROOT) {
  const a = css.indexOf(START);
  const b = css.indexOf(END);
  if (a < 0 || b < a) throw new Error('styles.css: @tablify-fonts markers not found');
  return css.slice(0, a) + fontBlock(root) + css.slice(b + END.length);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const file = path.join(ROOT, 'styles.css');
  const css = fs.readFileSync(file, 'utf8');
  const next = embed(css);
  if (process.argv.includes('--check')) {
    if (next !== css) {
      console.error('styles.css font block is stale: run `node scripts/embed-fonts.mjs`');
      process.exit(1);
    }
    console.log('Font embed check PASS');
  } else if (next !== css) {
    fs.writeFileSync(file, next);
    console.log(`styles.css: embedded ${FACES.length} faces (${next.length} bytes)`);
  } else {
    console.log('styles.css: font block already up to date');
  }
}
