// P4-03 accuracy report: runs inferColumn() on the labeled set and writes docs/reports/p4-03-accuracy.md.
// Run: npx tsx scripts/infer-accuracy.ts
// Numbers are reported as measured. Nothing is rounded up to meet the threshold (guidelines P4-03).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { inferColumn, type InferredType, type InputCell } from '../src/io/infer.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SET_PATH = join(ROOT, 'samples', 'fixtures', 'labeled', 'labeled-set.json');
const REPORT_PATH = join(ROOT, 'docs', 'reports', 'p4-03-accuracy.md');
const TYPES: InferredType[] = ['text', 'number', 'date', 'checkbox', 'single_select'];
const THRESHOLD = 0.9; // proposed (P4-03 acceptance), owner must confirm

interface LabeledColumn { name: string; label: InferredType; values: InputCell[] }
const raw = readFileSync(SET_PATH, 'utf8');
const expectedHash = JSON.parse(readFileSync(join(ROOT, 'samples', 'fixtures', 'HASHES.json'), 'utf8'))['labeled/labeled-set.json'];
const actualHash = createHash('sha256').update(raw).digest('hex');
if (actualHash !== expectedHash) throw new Error(`labeled set hash mismatch: ${actualHash} != ${expectedHash}`);
const set = JSON.parse(raw) as { rows: number; columns: LabeledColumn[] };

interface Run { column: LabeledColumn; inferred: InferredType; ratio: number; reason: string }
function run(tolerance: number): Run[] {
  return set.columns.map((c) => {
    const r = inferColumn(c.values, { tolerance });
    return { column: c, inferred: r.type, ratio: r.matchRatio, reason: r.reason };
  });
}

function metrics(runs: Run[]) {
  const per = Object.fromEntries(TYPES.map((t) => [t, { tp: 0, fp: 0, fn: 0 }])) as Record<InferredType, { tp: number; fp: number; fn: number }>;
  let correct = 0;
  for (const r of runs) {
    if (r.inferred === r.column.label) {
      correct++;
      per[r.column.label].tp++;
    } else {
      per[r.inferred].fp++;
      per[r.column.label].fn++;
    }
  }
  return { correct, total: runs.length, accuracy: correct / runs.length, per };
}

const strict = run(0);
const tolerant = run(0.05);
const mStrict = metrics(strict);
const mTol = metrics(tolerant);

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const ratio = (a: number, b: number) => (a + b === 0 ? 'n/a' : pct(a / (a + b)));

function perTypeTable(m: ReturnType<typeof metrics>): string {
  const rows = TYPES.map((t) => {
    const { tp, fp, fn } = m.per[t];
    return `| ${t} | ${tp + fn} | ${tp + fp} | ${tp} | ${ratio(tp, fp)} | ${ratio(tp, fn)} |`;
  });
  return ['| Type | Labeled | Predicted | Correct | Precision | Recall |', '|---|---|---|---|---|---|', ...rows].join('\n');
}

function columnTable(runs: Run[]): string {
  const rows = runs.map((r) => {
    const ok = r.inferred === r.column.label ? '✅' : '❌';
    return `| ${r.column.name} | ${r.column.label} | ${r.inferred} | ${ok} | ${pct(r.ratio)} | ${r.reason} |`;
  });
  return ['| Column | Labeled | Inferred | OK | Match ratio | Reason |', '|---|---|---|---|---|---|', ...rows].join('\n');
}

const misses = strict.filter((r) => r.inferred !== r.column.label);
const missLines = misses.map((r) => `- **${r.column.name}** — labeled \`${r.column.label}\`, inferred \`${r.inferred}\`. ${r.reason}`).join('\n');
const status = mStrict.accuracy >= THRESHOLD ? 'MET' : 'NOT MET';

const report = `# P4-03 — Type inference accuracy report

**Generated by:** \`npx tsx scripts/infer-accuracy.ts\`
**Labeled set:** \`samples/fixtures/labeled/labeled-set.json\` (sha256 \`${actualHash}\`, recorded in \`samples/fixtures/HASHES.json\`)
**Labeled set size:** ${set.columns.length} columns × ${set.rows} values (guidelines §P4-03: at least 30 columns × 100 values; C1 decision)
**Labeled set author:** the agent. Not independent of the rules (C5 decision). Read the numbers with that in mind.
**Rules under test:** \`src/io/infer.ts\` (see its header for the exact rules)

## Headline (strict rules, the default and the shipped behavior)

- Column accuracy: **${mStrict.correct} of ${mStrict.total} = ${pct(mStrict.accuracy)}**
- Acceptance threshold: ${pct(THRESHOLD)} (proposed) → **${status}**
- Owner decision needed: accept this result, or change the rules or the set (see "Decisions needed").

## Per-type precision and recall (strict)

${perTypeTable(mStrict)}

## Per-column results (strict)

${columnTable(strict)}

## Misclassifications (strict)

${missLines || '(none)'}

Causes, by design:
- **Noisy values under strict rules.** A single bad value (for example \`N/A\`, \`tbd\`, \`1,234.50\`) turns a numeric or date column into text, so no cell is lost on import. Noisy columns with few distinct values (\`maybe\`, \`???\`) fall back to single_select instead, which keeps every raw value as an option, so nothing is lost either. This data-safe behavior costs accuracy on noisy columns.
- **Hard cases, labeled as intended.** \`Comment\` (few distinct values, intended text) is inferred as single_select by the count rule. \`Team\` (25 options) is above the 20-option cap. \`Birthday\` is ambiguous-only dates (spec: ambiguous → text). \`Approved\` (Y/N) is outside the spec's word list, so it falls back to single_select.

## Sensitivity: 5% tolerance (NOT the default)

With \`tolerance = 0.05\`, columns may have up to 5% non-matching values. Those cells would be lost or altered on import, so this mode is for analysis only.

- Column accuracy at 5% tolerance: **${mTol.correct} of ${mTol.total} = ${pct(mTol.accuracy)}**

${perTypeTable(mTol)}

## Decisions needed (owner)

1. **C7 — noisy-column policy.** Strict (default, no data loss, lower accuracy) versus tolerant (higher accuracy, requires an import report and explicit data loss, or a text fallback for those cells). Recommend strict until the owner decides.
2. **Threshold.** Measured strict accuracy is ${pct(mStrict.accuracy)} against a proposed ${pct(THRESHOLD)}. Accept the measured result, or change the threshold, or change the labeled set. Changing the set after seeing results would be unsound, so any change must be decided before re-running.
3. **Pure 0/1 numeric columns** are classified as checkbox (spec literal: "checkbox from … 1/0"). A numeric column that only holds 0 and 1 will become a checkbox. Confirm this is acceptable.
4. **Ambiguous dates** (\`01/02/2026\`) are text, per spec. Users must reformat or the column stays text.
`;

mkdirSync(dirname(REPORT_PATH), { recursive: true });
writeFileSync(REPORT_PATH, report);
console.log(`strict accuracy: ${mStrict.correct}/${mStrict.total} (${pct(mStrict.accuracy)}) — threshold ${pct(THRESHOLD)} ${status}`);
console.log(`5% tolerance (sensitivity): ${mTol.correct}/${mTol.total} (${pct(mTol.accuracy)})`);
console.log(`per type (strict):`, Object.fromEntries(TYPES.map((t) => [t, mStrict.per[t]])));
console.log(`report written: ${REPORT_PATH}`);
